CREATE TABLE tbl_Files (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	Title NVARCHAR(100) NOT NULL,
	Extension NVARCHAR(10) NOT NULL,
	Path NVARCHAR(200) NOT NULL,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);